version: '3'
services:
  app:
    image: node:9.9.0
    command: npm run dev:start
    environment:
      - NODE_ENV=development
    working_dir: '/usr/local/app'
    volumes:
      - .:/usr/local/app
    ports:
      - '3000:3000'
      - '4587:4587'
      - '9229:9229'
    links:
      - mongodb
    networks:
      - default
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.3-jessie
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
